apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deploy
  labels:
    env: prod
spec:
  selector:
    matchLabels:
      env: prod      
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-pod
        env: prod
        
    spec:
      containers:
      - name: app-container
        image: sadanchandra99/productimages:1.1 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
       