# declare a service object
apiVersion: v1
kind: Service
metadata:
  name: website-svc
  labels:
    app: app-apache
    version: v1.1
    env: dev
# define and configure service to acces 80 port
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 32401
    protocol: TCP
  selector:
    env: dev