apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deploy
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      env: dev      
  replicas: 2
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: website-pod
        env: dev
        
    spec:
      containers:
      - name: website-container
        image: sadanchandra99/websiteimages:2.0 
        imagePullPolicy: Always
        ports:
        - containerPort: 80
       